spring:
  application:
    name: "InfoStorage"
  messages:
    basename: messages
    encoding: UTF-8

      
app:
  header: "data"
  cloud: "store"
  freaz-tag: "freaz"
  data:
    mainURI: "redis://172.24.121.136:6379/1"